---
name: Run Unit Tests

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Application

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Build doker image
        run: |
          cd node
          docker build -t temp/build .
      - name: Login
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push docker image
        run: |
          docker tag temp/build benishere/cicdassignment:latest
          docker tag temp/build benishere/cicdassignment:${{ github.sha }}
          docker push benishere/cicdassignment:latest
          docker push benishere/cicdassignment:${{ github.sha }}
        